### ISSUE TITLE
file not found in build context or excluded by .dockerignore: stat assets//nasl-cli: file does not exist

### ISSUE THREAD

**Issue by prosinger** [greenbone/openvas-scanner#1511]
Building a docker image:
1) git clone https://github.com/greenbone/openvas-scanner.git
2) cd openvas-scanner/
3) docker build -t openvas -f .docker/prod.Dockerfile .

...

3)
Step 14/25 : COPY assets/$TARGETPLATFORM/nasl-cli /usr/local/bin/nasl-cli
COPY failed: file not found in build context or excluded by .dockerignore: stat assets//nasl-cli: file does not exist

Edit by ArnoStiefvater: Internal tracking SC-933

**Comment by jjnicola** [comment]
Hello @prosinger ,

Thanks for reporting this issue.
Looking into the docker file, there is a note which clarifies the problem: binaries are built within CI and therefore it is ensured that the images provided by greenbone work as expected.
In your case, if you want to manually build your own images, you will have to pre build the `nasl-cli ` and `openvas` binaries and copy them in the right folder. 
I have tested in my development environment and I was able to reproduce the issue, but just copying the binaries into `assets/linux/amd64/`, the problem is solved.

For building the binaries you will need to do the following steps:
- install the rust toolchain
```shell
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
source "$HOME/.cargo/env"
```
- Assuming you are the openvas project root folder, create the assets folder for your architecture, e.g.:
``` shell
mkdir -p assets/linux/amd64
``` 
- build and copy the `nasl-cli` in the assets folder
``` shell
cargo install --path rust/nasl-cli
cp $HOME/.cargo/bin/nasl-cli assets/linux/amd64/
```
- build and copy the `openvasd` in the assets folder
``` shell
cargo install --path rust/openvasd
cp $HOME/.cargo/bin/openvasd assets/linux/amd64/
```

Now you can build the docker images.
This is not considered bug, since our docker files are intended to be use in CI process for creation of images and it is expected and documented that if you build your own images, you have to provide the missing binaries. Therefore, I removed the bug flag.

I hope this help. 
Best regards,

Juan
