### ISSUE TITLE
/usr/sbin/openvassd: undefined symbol: nvticache_get_by_name_full

### ISSUE THREAD

**Issue by wsw70** [greenbone/openvas-scanner#173]
### Expected behavior

`systemctl start openvas-scanner` succeeds

### Current behavior

It fails with the following error message

    Sep 19 14:27:29 ery openvassd[30420]: /usr/sbin/openvassd: symbol lookup error: /usr/sbin/openvassd: undefined symbol: nvticache_get_by_name_full

### GVM versions

The installation was done on Ubuntu bionic via `apt install openvas`

**gsa:** 7.0.2

**gvm:** not installed

**openvas-scanner:**

    root@ery:~# openvassd --version
    openvassd: symbol lookup error: openvassd: undefined symbol: nvticache_get_by_name_full

**gvm-libs:**

**openvas-smb:**

### Environment
**Operating system:** Ubuntu 18.04.1 bionic

**Installation method / source:** package

### Logfiles

```
-- Unit openvas-scanner.service has begun starting up.
Sep 20 09:11:20 ery openvassd[31785]: /usr/sbin/openvassd: symbol lookup error: /usr/sbin/openvassd: undefined symbol: nvticache_get_by_name_full
Sep 20 09:11:20 ery systemd[1]: openvas-scanner.service: Control process exited, code=exited status=127
Sep 20 09:11:20 ery systemd[1]: openvas-scanner.service: Failed with result 'exit-code'.
Sep 20 09:11:20 ery systemd[1]: Failed to start Open Vulnerability Assessment System Scanner Daemon.
-- Subject: Unit openvas-scanner.service has failed

```

**Comment by cfi-gb** [comment]
@wsw70 Please note this is a bugtracker and not an support channel, the new community you have cross-posted this issue:

https://community.greenbone.net/t/undefined-symbol-nvticache-get-by-name-full-when-starting-the-scanner/319

can be used until it is really confirmed that this is a bug.

But in this case the message itself is showing that you're using an openvassd trying to use a "nvticache_get_by_name_full" function which isn't provided by your used openvas-libraries.

This happens if e.g. you're mixing a version of openvas-scanner 5.1.1 with a version of openvas-libraries-9.0.3 or higher.

Please close here and contact the maintainer of your used packages (e.g. via the Launchpad bugtracker) to get the packages updated.

**Comment by wsw70** [comment]
@cfi-gb : sorry if this is the wrong channel. I was under the impression that if the software does not start at all and issues an error message about missing symbols in the binaries that would be classified as bug.

I initially posted in the forum, not realizing that there is a bug tracker.

Thank you for the explanation, I will try to build from scratch in that case.

**Comment by cfi-gb** [comment]
@wsw70 Thanks for helping to keep the communication channels clean.

Fom my experience its the best to first ask for some help in a community of the software you're using (e.g. https://community.greenbone.net). The more experienced users can then help to decide if you have indeed faced a bug which could be forwarded to a bugtracker like the one here or if its just a configuration / environmental issue.

This helps to keep the issue tracker clean from configuration / environmental issues and to keep the focus on the actual reported and confirmed bugs.
