### ISSUE TITLE
Ubuntu Update for linux USN-3847-1 (Shows wrong kernel)

### ISSUE THREAD

**Issue by featzor** [greenbone/openvas-scanner#280]
First of hello, first timer here (if I did report the issue in wrong channel, please direct me to correct channel). Did run a full scan with credentials today and received the alert of a severity of 7.2. However, reading the description it displays wrong kernel version.

Running a full scan with updated NVTs:

Ubuntu Update for linux USN-3847-1 | Ubuntu Local Security Checks | Fri Dec 21 2018 | **Tue Feb 5 2019** | $Revision: 13454 $ | CVE-2018-10902 CVE-2018-12896 CVE-2018-14734 CVE-2018-16276 CVE-2018-18445 CVE-2018-18690 CVE-2018-18710

Displays wrong kernel installed.

### Expected behavior

Pass. Displays wrong installed kernel.
$ uname -r
$ **4.15.0-45-generic**

### Current behavior

High (CVSS: 7.2)
NVT: Ubuntu Update for linux USN-3847-1 (OID: 1.3.6.1.4.1.25623.1.0.843856)
Summary

The remote host is missing an update for the 'linux' package(s) announced via the USN-3847-1 advisory.
Vulnerability Detection Result

Vulnerable package: linux-image-4.15.0-42-generic
**Installed version:  4.15.0-42.45**
Fixed version:      4.15.0-43.46

### GVM versions
**gsa: 7.0.3**

**openvas-scanner: 5.1.3**

### Environment
**Operating system: Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-45-generic)**

**Installation method / source: ppa:mrazavi/openvas, libopenvas9-dev, ** (packages, source installation)

**Comment by cfi-gb** [comment]
Thanks for your report. This is indeed a wrong channel to report this because this is a report about a VT doing the reporting and not about the scanner itself.

Generally reports about VTs and and possible issues within these should go into https://community.greenbone.net/c/vulnerability-tests

However in your specific case the output is correct and expected. You have an old version of the linux-image-4.15.0-42-generic which is not active and thus not active (and reported via uname).

Such vulnerable but inactive kernel packages are still imposing a risk for your environment so those are reported as a vulnerability correctly. If you want to accept the risk of such a kerne package you can work with an overwrite to lower the log level.

If you have further questions on this topic please create a new thread at the linked community portal.

Thanks again for your report.

**Comment by featzor** [comment]
Thank you for the feedback and where to turn in future! and thanks for the great scanner 👍
