### ISSUE TITLE
[6.0.0] Version comp doe's not work correct for rpm packages.

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/openvas-scanner#319]
### Expected behavior
The the versions of installed packages are correct detected

### Current behavior
An newer package is detected as an older one.

### Steps to reproduce
Scan the system with ssh credentials.

### GVM versions
**gsa:** (gsad --version)
8.0.0~git

**gvm:** (gvmd --version)
8.0.0

**openvas-scanner:** (openvassd --version)
6.0.0

**gvm-libs:**
10.0.0

**openvas-smb:**
1.0.5

### Environment
**Operating system:**
CentOS 7.6

**Installation method / source:** (packages, source installation)
Git

### Logfiles
Result of scan: 
 CentOS Update for iwl1000-firmware CESA-2018:0094 centos7 OID: 1.3.6.1.4.1.25623.1.0.882829

Vulnerable package: iwl5000-firmware
Installed version:  iwl5000-firmware-8.83.5.1_1-69.el7
Fixed version:      iwl5000-firmware-8.83.5.1_1-58.el7_4

**Comment by cfi-gb** [comment]
Thanks for your report. I'm closing this issue as "invalid" because the scanner is only executing .nasl scripts and is e.g. not responsible for such comparisons. 

If you're facing issues with VTs please report it directly to the following community portal category:

https://community.greenbone.net/c/vulnerability-tests
