### ISSUE TITLE
cmake don't check for gpgme and libpcap

### ISSUE THREAD

**Issue by tuxmaster** [greenbone/openvas-scanner#5]
cmake don't check for the both libs.
So build it in clean chroot environment.
It will fail with:
/usr/include/openvas/base/gpgme_util.h:36:19: fatal error: gpgme.h: No such file or directory
 #include <gpgme.h>
/usr/include/openvas/misc/pcap_openvas.h:29:18: fatal error: pcap.h: No such file or directory
 #include <pcap.h>

**Comment by jjnicola** [comment]
Hello tuxmaster,
In openvas-scanner-5.1 branch are not checked since they are check for openvas-libraries-9.0

-- Looking for pcap...
-- Looking for pcap... PCAP-NOTFOUND
CMake Error at CMakeLists.txt:201 (message):
  The pcap library is required.


-- Looking for pcap-config...
-- pcap-config not found, using defaults...
-- Looking for gpgme...
-- Looking for gpgme... GPGME-NOTFOUND
CMake Error at CMakeLists.txt:230 (message):
  The gpgme library is required.

In master branch:

-- Looking for pcap...
-- Looking for pcap... PCAP-NOTFOUND
CMake Error at misc/CMakeLists.txt:41 (message):
  The pcap library is required.


-- Looking for pcap-config...
-- pcap-config not found, using defaults...
-- Looking for gpgme...
-- Looking for gpgme... GPGME-NOTFOUND
CMake Error at misc/CMakeLists.txt:69 (message):
  The gpgme library is required.

gpgme is also checked for gvm-libs, which are requiered too.

Regards,
Juan

**Comment by jjnicola** [comment]
Hello @tuxmaster. Close the issue here. If you find that the issue persists, please create a new one providing the information asked in the issue template.
