### ISSUE TITLE
GVM 20.08.1 alive test problems

### ISSUE THREAD

**Issue by karkaaa** [greenbone/openvas-scanner#683]
### GVM versions

**gsa:** 20.08.1

**gvm:** 20.08.1

**openvas:** 20.08.1

**gvm-libs:** 20.08.1

**openvas-smb:** 1.0.5

**ospd-openvas:** 20.08.1

### Environment

**Operating system:** Debian 10

**Installation method / source:** source

### Logfiles

openvas.log - The remote host XXX.XXX.XXX.XXX is dead.

Not working "Alive test" with "ARP Ping" or "Consider Alive" but then i try manual arping everything working and can reach by telnet host.

It is bug?

Thank you.

**Comment by cfi-gb** [comment]
Have a look at the following:

```
1. Be aware that this is not a support forum. If your issue is rather a question
   than a bug report, please use our community forum at
   https://community.greenbone.net/c/gse instead.
```

Closing this as invalid for now, especially this might be an environmental issue (e.g. SELinux, missing nmap, ...). Please open a new topic at https://community.greenbone.net/c/gse for support. Once it has been found to be a real bug we can still re-open this issue here.
